import { TemplatePage } from "./TemplatePage/TemplatePage"
import { HomePage } from "./HomePage/HomePage"
import { SingleVideoPage } from "./SingleVideoPage/SingleVideoPage"
import { LoginPage } from "./AuthPages/LoginPage"
import { SignupPage } from "./AuthPages/SignupPage"
import { LogoutPage } from "./AuthPages/LogoutPage"
import { LikedVideoPage } from "./LikedVideoPage/LikedVideoPage"
import { HistoryPage } from "./HistoryPage/HistoryPage"
import { PlaylistPage } from "./PlaylistPage/PlaylistPage"
export { LoginPage, TemplatePage, HomePage, SingleVideoPage, SignupPage, LogoutPage, LikedVideoPage, HistoryPage, PlaylistPage}
